### ISSUE TITLE
Referencing version from empty file

### ISSUE THREAD

**Issue by farmio** [ziv1234/dynalitepanel#1]
https://github.com/ziv1234/dynalitepanel/blob/f5474ee7356908ca032c128bdb61894486e7f6e4/build-scripts/env.js#L26-L30

Hi 👋! 
This seems to be a leftover from moving to pyproject.toml. The referenced file is empty, so `version` will always be falsy.

**Comment by ziv1234** [comment]
thanks. I believe this is from the copy/paste and I am not really using it. deleted from the code. will do some testing and push a version without it. I couldn't find anywhere that references it

**Comment by ziv1234** [comment]
code pushed. will make it into the next release as it doesn't change behavior, but simply removes unnecessary build scripts.
Thanks!
